In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import json
from pandas import json_normalize

In [2]:
page = 100

id_ = []
name = []
brand = []
volume = []
price = []
best_loyalty_price = []

for i in range(0, page+1):
    
    URL = f'https://api.rivegauche.ru/rg/v1/newRG/products/search?fields=FULL&currentPage=0&pageSize=24&categoryCode=Perfumery_Men&tag=4108894044469370'
    data = requests.get(URL)
    print(data.status_code)
    soup = BeautifulSoup(data.text, 'html.parser') # получаем суп страницы 
    
    data = json.loads(str(soup)) # преобразовываем файл суп в файл json 
    
    for j in range(len(data['results'])):
    
        id_.append(data['results'][j]['code']) # создаем cписки
        name.append(data['results'][j]['name']) # создаем cписки
        brand.append(data['results'][j]['manufacturer']) # создаем cписки
        
        if data['results'][j]['classifications'][0]['features'][3]['featureValues'][0]['value'] != "": # создаем cписки
            volume.append(data['results'][j]['classifications'][0]['features'][3]['featureValues'][0]['value'])
        else:
            volume.append('нет объема')
            
        price.append(data['results'][j]['prices'][2]['value']) # создаем cписки
        
        try:
            best_loyalty_price.append(data['results'][j]['price']['value']) # создаем cписки
            
        except:
            best_loyalty_price.append('нет скидки')

200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200
200

In [3]:
df=pd.DataFrame() # создаем дф

df['id'] = id_ # добавляем столбцы в дф
df['name'] = name # добавляем столбцы в дф
df['brand'] = brand # добавляем столбцы в дф
df['volume'] = volume # добавляем столбцы в дф
df['price'] = price # добавляем столбцы в дф
df['best_loyalty_price'] = best_loyalty_price # добавляем столбцы в дф

In [4]:
df.loc[:, "shop"] = 'Рив Гош' # добавляем столбцес магазином

In [5]:
df.head()

,id,name,brand,volume,price,best_loyalty_price,shop
0,982102,El Ganso Limoncello Season Eau de Toilette Tra...,EL GANSO,15,1750.0,1750.0,Рив Гош
1,942565,Beverly Hills Polo Club Titan Eau de Parfum,BEVERLY HILLS POLO CLUB,Парфюмерия,5550.0,5550.0,Рив Гош
2,864847,Adopt Blue Suit Eau De Parfum,ADOPT’,30,950.0,950.0,Рив Гош
3,969972,Dior Sauvage Elixir Parfum,DIOR,мужчин,13700.0,13700.0,Рив Гош
4,876201,Maori Collection Life Circle Eau De Parfum,MAORI COLLECTION,100,7700.0,7700.0,Рив Гош

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2424 entries, 0 to 2423
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  2424 non-null   object
 1   name                2424 non-null   object
 2   brand               2424 non-null   object
 3   volume              2424 non-null   object
 4   price               2424 non-null   float64
 5   best_loyalty_price  2424 non-null   float64
 6   shop                2424 non-null   object
dtypes: float64(2), object(5)
memory usage: 132.7+ KB

In [7]:
df.to_csv('prices_riv_gosh.csv', sep=',', encoding='utf-8')